version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: umbrel-peppermint_peppermint_1
      APP_PORT: 3000
    
  peppermint:
    image: pepperlabs/peppermint:latest
    user: "1000:1000"
    init: true
    restart: always
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'

  peppermint_postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /DATA/AppData/peppermint/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint
